export const types = {
  FORM_SEND: "FORM_SEND",
  NAME_CHANGE: "NAME_CHANGE",
  USER_NAME_CHANGE: "USER_NAME_CHANGE",
  E_MAIL_CHANGE: "E_MAIL_CHANGE",
  WEB_SITE_CHANGE: "WEB_SITE_CHANGE",
  IS_OK_CHANGE: "IS_OK_CHANGE",
  IS_SHOWING_CHANGE: "IS_SHOWING_CHANGE",
  CLEAR_FORM: "CLEAR_FORM",
};
