export const types = {
  CHANGE_TODO_INPUT: "CHANGE_TODO_INPUT",
  ADD_TODO: "ADD_TODO",
  DELETE_TODO: "DELETE_TODO",
  CHANGE_STATUS: "CHANGE_STATUS",
  CHANGE_TITLE: "CHANGE_TITLE",
  USERS: "USERS",
};
